#!/bin/sh
# chkconfig: 345 80 20
# description: Ceilometer Collector

bin="/usr/bin"
conf="/etc/ceilometer"
. /etc/init.d/functions

start() {
	echo -n Starting Ceilometer API:
	daemon --user=ceilometer $bin/ceilometer-collector
	retval=$?
	echo
	[ "$retval" = 0 ] && touch /var/lock/subsys/ceilometer-collector
	return $retval
}

stop() {
	echo -n Stopping Ceilometer Collector:
	killproc ceilometer-collector
	retval=$?
	echo
	[ "$retval" = 0 ] && rm -f /var/lock/subsys/ceilometer-collector
	return $retval
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status ceilometer-collector
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: ceilometer-collector {start|stop|status|restart}"
		exit 1
		;;
esac

exit 0
