#!/bin/sh
# chkconfig: 345 80 20
# description: Ceilometer Agent Central

bin="/usr/bin"
conf="/etc/ceilometer"
. /etc/init.d/functions

start() {
	echo -n Starting Ceilometer Agent Central:
	daemon --user=ceilometer $bin/ceilometer-agent-central
	retval=$?
	echo
	[ "$retval" = 0 ] && touch /var/lock/subsys/ceilometer-agent-central
	return $retval
}

stop() {
	echo -n Stopping Ceilometer Agent Central:
	killproc ceilometer-agent-central
	retval=$?
	echo
	[ "$retval" = 0 ] && rm -f /var/lock/subsys/ceilometer-agent-central
	return $retval
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status ceilometer-agent-central
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: ceilometer-agent-central {start|stop|status|restart}"
		exit 1
		;;
esac

exit 0
