#!/bin/sh
# chkconfig: 345 80 20
# description: Ceilometer API

bin="/usr/bin"
conf="/etc/ceilometer"
. /etc/init.d/functions

start() {
	echo -n Starting Ceilometer API:
	daemon --user=ceilometer $bin/ceilometer-api
	retval=$?
	echo
	[ "$retval" = 0 ] && touch /var/lock/subsys/ceilometer-api
	return $retval
}

stop() {
	echo -n Stopping Ceilometer API:
	killproc ceilometer-api
	retval=$?
	echo
	[ "$retval" = 0 ] && rm -f /var/lock/subsys/ceilometer-api
	return $retval
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status ceilometer-api
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: ceilometer-api {start|stop|status|restart}"
		exit 1
		;;
esac

exit 0
